---
title: "Trebuchet?!"
author: "Aman Das"
format: html
---

## Introduction

Ok so first part was fairly simple, let's tackle the string recognition version.
How hard could it be?

**TODO:**

-   Import data a vector of strings
-   Extract digits
-   extract the first digit
-   extract the last digit
-   merge them
-   Add them

```{r}
library(stringr)
library(dplyr)
library(readr)
```

## Import data

```{r}
list_str = read_delim("part1.txt", delim = "\n", col_names = FALSE)
list_str = list_str$X1
```

## Extract digits

```{r}
get_num = function(word){
  res = c()
  ref = c("one",
         "two",
         "three",
         "four",
         "five",
         "six",
         "seven",
         "eight",
         "nine")
  digs = as.character(1:9)
  letters = c( str_split_1(word, "") )
  l = length( letters )
  
  for ( i in 1:l ) { # loop over the letters
    
    letter = letters[i]
    
    if ( letter %in% digs) { # is letter a digit
      res = append(res, letter)
      
    } else {
      
      startcheck = startsWith( substring(word, i), ref) # check start of number
      
      if ( TRUE %in% startcheck ){
        res = append( res, match(TRUE, startcheck) )
      }
    }

  }
  
  return( as.numeric(res) )
}
list_num = sapply(list_str, get_num)
```

## Extract first and last digits

```{r}
list_1 = sapply(list_num, first)
list_2 = sapply(list_num, last)
```

## Merge the lists

```{r}
list_res = 10*list_1+list_2
```

## Add the numbers

```{r}
res = sum(list_res)
```

## Export to output file

```{r}
write_lines(res, "output.txt")
```
